# Generated by Django 3.0.2 on 2022-09-19 06:42

import dashboard.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=16)),
                ('mandate', models.TextField(blank=True)),
                ('account_purpose', models.CharField(blank=True, max_length=255)),
                ('is_saving_account', models.BooleanField(default=True)),
                ('is_current_account', models.BooleanField(default=False)),
                ('is_closed_account', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_photo', models.ImageField(blank=True, null=True, upload_to='passort_pic/%y-%m-%d/', validators=[dashboard.validators.validate_image_extension])),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('name', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced')], max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('place_of_birth', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Ghanaian', max_length=200)),
                ('hometown', models.CharField(max_length=200, null=True)),
                ('region_or_state', models.CharField(max_length=200, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('ssnit_number', models.CharField(max_length=13, null=True)),
                ('tin_number', models.CharField(max_length=11, null=True)),
                ('residential_address', models.CharField(max_length=255, null=True)),
                ('residential_city', models.CharField(max_length=100, null=True)),
                ('residential_region', models.CharField(max_length=200, null=True)),
                ('residential_phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +233', regex='^\\+?1?\\d{9,15}$')])),
                ('residential_status', models.CharField(choices=[('Owned', 'Owned'), ('Rented', 'Rented'), ('Lodging', 'Lodging'), ('Family', 'Family')], max_length=20)),
                ('national_identity', models.CharField(choices=[('Voter Id', 'Voter Id'), ('National Passport', 'National Passport'), ('NHIS', 'NHIS'), ('ECOWAS Card', 'ECOWAS Card')], max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('id_issue_date', models.DateField()),
                ('id_expiry_date', models.DateField()),
                ('country_of_issue', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employment_type', models.CharField(choices=[('Employed', 'Employed'), ('Self Employment', 'Self Employment'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Student', 'Student')], max_length=20)),
                ('city_of_employment', models.CharField(max_length=100, null=True)),
                ('region_of_employment', models.CharField(max_length=200, null=True)),
                ('nature_of_business', models.CharField(max_length=200, null=True)),
                ('nxt_of_kin_name', models.CharField(max_length=200, null=True)),
                ('nxt_of_kin_contact', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +233', regex='^\\+?1?\\d{9,15}$')])),
                ('relation_with_kin', models.CharField(max_length=200, null=True)),
                ('nxt_of_kin_residence', models.CharField(max_length=200, null=True)),
                ('nxt_of_kin_region', models.CharField(max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +233', regex='^\\+?1?\\d{9,15}$')])),
                ('relation_with_emergency_contact', models.CharField(max_length=200, null=True)),
                ('emergency_contact_residence', models.CharField(max_length=200, null=True)),
                ('emergency_contact_region', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Withdrawals', to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='clients.Client')),
            ],
        ),
    ]
