# Generated by Django 3.0.2 on 2022-09-19 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='region_or_state',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='country_of_issue',
            new_name='county_of_issue',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='residential_region',
            new_name='residential_county',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ssnit_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tin_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +254', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_identity',
            field=models.CharField(choices=[('National Id Number', 'National Id Number'), ('Passport Number', 'Passport Number')], max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='nxt_of_kin_contact',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +254', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='residential_phone',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +254', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
