# Generated by Django 3.0.2 on 2022-09-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20220919_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nxt_of_kin_contact',
            new_name='next_of_kin_contact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nxt_of_kin_name',
            new_name='next_of_kin_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nxt_of_kin_region',
            new_name='next_of_kin_region',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nxt_of_kin_residence',
            new_name='next_of_kin_residence',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='relation_with_emergency_contact',
            new_name='relation_with_next_of_kin',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='relation_with_kin',
            new_name='relationship_with_emergency_contact',
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(default='Kenyan', max_length=200),
        ),
    ]
