# Generated by Django 3.0.2 on 2022-09-19 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('opening_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('Ashanti Region', 'Ashanti Region'), ('Bono Region', 'Bono Region'), ('Bono East', 'Bono East'), ('Ahafo Region', 'Ahafo Region'), ('Central Region', 'Central Region'), ('Eastern Region', 'Eastern Region'), ('Greater Accra', 'Greater Accra'), ('Northern Region', 'Northern Region'), ('Savannah Region', 'Savannah Region'), ('North East', 'North East'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta Region', 'Volta Region'), ('Oti Region', 'Oti Region'), ('Western Region', 'Western Region'), ('Western North', 'Western North')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +233', regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branch Name',
                'verbose_name_plural': 'Branch Names',
            },
        ),
    ]
