# Generated by Django 3.0.2 on 2022-09-19 22:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='region',
        ),
        migrations.AddField(
            model_name='branch',
            name='county',
            field=models.CharField(choices=[('Nairobi', 'Nairobi'), ('Uasin Gishu', 'Uasin Gishu'), ('Bomet', 'Bomet'), ('Kericho', 'Kericho'), ('West Pokot', 'West Pokot'), ('Siaya', 'Siaya'), ('Nakuru', 'Nakuru'), ('Kiambu', 'Kiambu'), ('Kajiado', 'Kajiado'), ('Taita Taveta', 'Taita Taveta'), ('Elgeiyo Marakwet', 'Elgeiyo Marakwet'), ('Samburu', 'Samburu'), ('Kisii', 'Kisii'), ('Narok', 'Narok'), ('Mombasa', 'Mombasa'), ('Baringo', 'Baringo'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Garrissa', 'Garrissa'), ('Marsabit', 'Marsabit'), ('Mandera', 'Mandera'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Kitui', 'Kitui'), ('Embu', 'Embu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', 'Muranga'), ('Turkana', 'Turkana'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Nandi', 'Nandi'), ('Laikipia', 'Laikipia'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Kisumu', 'Kisumu'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Homabay', 'Homabay')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number invalid. Should start with example: +233', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
